[theme]
primaryColor = "#00f3ff"
backgroundColor = "#090d16"
secondaryBackgroundColor = "#0d1322"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
